// AUTO-GENERATED by tools/gen_music_manifest.mjs — do not edit by hand.
// The list of track ids that have a produced MP3 in public/music/<id>.mp3.
// Empty = the game plays its procedural synth music for every track (default).
// Drop MP3s in public/music/ and re-run the generator to populate this.
export const MUSIC_FILES = ["hub","title","w1","w2","w3","w4"];
