// AUTO-GENERATED by tools/gen_sfx_manifest.mjs — do not edit by hand.
// Map of sfx voice name -> file extension for produced samples in public/sfx/.
// Empty = every sound uses its procedural synth voice (default). Drop
// public/sfx/<name>.wav (or .mp3) and re-run the generator to populate this.
export const SFX_SAMPLES = {};
