// AUTO-GENERATED by tools/gen_vo.mjs — do not edit by hand.
// Maps a normalized on-screen caption (see voKey() in vo.js) to its VO clip id
// under public/vo/<id>.mp3. Only lines with a generated mp3 appear here.
export const VO_LOOKUP = {
  "welcome to mandatory orientation i am kobi  keeper of building integrity the buildings integrity is currently: annoyed": "tut_start",
  "touch the sparky floor and we simply rebuild you at the last checkpoint it is painless mostly it is mostly painless": "tut_hazard",
  "those pedestals hold your gadgets walk up and press your action key  space or l  to equip mind the paint": "tut_gadget",
  "grapple zips the gap; heavy stomps the cracked floor to drop a bridge your gadget helps your buddy teamwork ugh": "tut_teamwork",
  "and if youre ever truly wedged  hold r twice to restart the room it is fine a little sad but fine esc bails you back to the map": "tut_restart",
  "you pass statistically improbable now get out of my lobby": "tut_clear",
  "welcome to my assembly wing little trespassers take those silly gadgets if you must the puppy is confiscated": "l1_1_start",
  "a grappling hook and a heavy chassis how quaint the lift ahead needs serious weight you know": "l1_1_skills",
  "you cleared one chamber i have eleven more i am not worried not worried": "l1_1_clear",
  "ah the crusher line i flattened four hundred defective toasters here it is my favorite chamber": "l1_2_start",
  "behold my magnificent crane it has four stars on labreviewsdotcom say hello crane it says hello": "l1_3_start"
};
