// VO generator — turns tools/vo_lines.mjs into public/vo/<id>.mp3 via xAI TTS,
// and regenerates src/audio/vo_manifest.js (the caption -> clip-id lookup).
//
// Idempotent & cached: each clip is written alongside a <id>.json holding the
// request hash. On re-run, a line whose request (voice+emotion+instructions+
// speak+speed) is unchanged is SKIPPED — so editing one line re-cuts only that
// clip, and a full re-run after a fresh checkout costs nothing if mp3s exist.
//
// Key: read from $XAI_API_KEY, else the session scratchpad file. NEVER committed.
//
// Usage:
//   node tools/gen_vo.mjs            # generate any missing/changed clips
//   node tools/gen_vo.mjs --force    # re-cut every clip regardless of cache
//   node tools/gen_vo.mjs --only id1,id2   # only these ids
//   node tools/gen_vo.mjs --manifest-only  # just rebuild the manifest from disk

import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LINES, VOICES, PERSONA } from "./vo_lines.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const VO_DIR = path.join(ROOT, "public", "vo");        // ships: mp3s only
const CACHE = path.join(ROOT, "tools", "vo_cache.json"); // committed, NOT shipped
const MANIFEST = path.join(ROOT, "src", "audio", "vo_manifest.js");
const TTS_URL = "https://api.x.ai/v1/tts";
const SCRATCH_KEY =
  "/tmp/claude-0/-home-user-NewVoices-Demo/69af6ac3-3815-580d-ba49-a5ef683f1c9e/scratchpad/.xai_key";

const argv = process.argv.slice(2);
const FORCE = argv.includes("--force");
const MANIFEST_ONLY = argv.includes("--manifest-only");
const ONLY = (() => {
  const i = argv.indexOf("--only");
  return i >= 0 && argv[i + 1] ? new Set(argv[i + 1].split(",")) : null;
})();

// Must match voKey() in src/audio/vo.js EXACTLY so a live caption finds its clip.
function voKey(s) {
  return String(s == null ? "" : s)
    .replace(/^\s*[A-Z][A-Z0-9 ._-]{0,14}:\s*/, "")
    .toLowerCase()
    .replace(/[\s]+/g, " ")
    .replace(/[.!?…,"'’—-]+/g, "")
    .trim();
}

function buildRequest(line) {
  const voice = VOICES[line.speaker];
  const instructions = `${PERSONA[line.speaker]} ${line.extra || ""}`.trim();
  const body = { text: line.speak, language: "en", voice, emotion: line.emotion, instructions };
  if (line.speed && line.speed !== 1.0) body.speed = line.speed;
  return body;
}

function reqHash(body) {
  return createHash("sha256").update(JSON.stringify(body)).digest("hex").slice(0, 16);
}

async function getKey() {
  if (process.env.XAI_API_KEY) return process.env.XAI_API_KEY.trim();
  try {
    return (await fs.readFile(SCRATCH_KEY, "utf8")).trim();
  } catch {
    throw new Error(
      "xAI API key not found. Set $XAI_API_KEY or restore the scratchpad key file."
    );
  }
}

async function exists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

async function loadCache() {
  try { return JSON.parse(await fs.readFile(CACHE, "utf8")); } catch { return {}; }
}

async function generateOne(key, line, cache) {
  const body = buildRequest(line);
  const hash = reqHash(body);
  const mp3Path = path.join(VO_DIR, `${line.id}.mp3`);

  if (!FORCE && cache[line.id]?.hash === hash && (await exists(mp3Path))) {
    return { id: line.id, status: "cached" };
  }

  const res = await fetch(TTS_URL, {
    method: "POST",
    headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const t = await res.text().catch(() => "");
    throw new Error(`TTS ${res.status} for ${line.id}: ${t.slice(0, 200)}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 512) throw new Error(`TTS returned ${buf.length}B for ${line.id} (too small)`);
  await fs.writeFile(mp3Path, buf);
  cache[line.id] = { hash, voice: body.voice, emotion: body.emotion, bytes: buf.length };
  return { id: line.id, status: "generated", bytes: buf.length };
}

async function rebuildManifest() {
  // Map voKey(trigger) -> id, but only for lines whose mp3 actually exists on disk.
  const entries = [];
  for (const line of LINES) {
    if (!line.trigger) continue;
    if (!(await exists(path.join(VO_DIR, `${line.id}.mp3`)))) continue;
    entries.push([voKey(line.trigger), line.id]);
  }
  const seen = new Map();
  for (const [k, id] of entries) {
    if (seen.has(k)) console.warn(`  ⚠ duplicate caption key -> ${seen.get(k)} & ${id}: "${k}"`);
    seen.set(k, id);
  }
  const lookup = Object.fromEntries(seen);
  const src =
    "// AUTO-GENERATED by tools/gen_vo.mjs — do not edit by hand.\n" +
    "// Maps a normalized on-screen caption (see voKey() in vo.js) to its VO clip id\n" +
    "// under public/vo/<id>.mp3. Only lines with a generated mp3 appear here.\n" +
    `export const VO_LOOKUP = ${JSON.stringify(lookup, null, 2)};\n`;
  await fs.writeFile(MANIFEST, src);
  return Object.keys(lookup).length;
}

async function main() {
  await fs.mkdir(VO_DIR, { recursive: true });

  if (!MANIFEST_ONLY) {
    const key = await getKey();
    const cache = await loadCache();
    const targets = LINES.filter((l) => !ONLY || ONLY.has(l.id));
    let gen = 0, cached = 0, failed = 0;
    for (const line of targets) {
      try {
        const r = await generateOne(key, line, cache);
        if (r.status === "generated") { gen++; console.log(`  ✓ ${line.id.padEnd(16)} generated (${r.bytes}B)`); }
        else { cached++; console.log(`  · ${line.id.padEnd(16)} cached`); }
      } catch (e) {
        failed++; console.error(`  ✗ ${line.id.padEnd(16)} ${e.message}`);
      }
    }
    await fs.writeFile(CACHE, JSON.stringify(cache, null, 2) + "\n");
    console.log(`\n  generated ${gen}, cached ${cached}, failed ${failed}`);
    if (failed) process.exitCode = 1;
  }

  const n = await rebuildManifest();
  console.log(`  manifest: ${n} caption(s) -> clip id  ->  ${path.relative(ROOT, MANIFEST)}`);
}

main().catch((e) => { console.error(e.message || e); process.exit(1); });
