// Scan public/music/*.mp3 and regenerate src/audio/music_manifest.js — the list of
// track ids that have a produced MP3. Run this after adding or removing music files:
//
//   node tools/gen_music_manifest.mjs
//
// Track ids the game asks for (see src/audio/music.js): title, hub, w1l1, w1l2,
// w1l3, w2l1, w2l2, w2l3, w3, w4. A per-world file (w1.mp3) covers all that world's
// levels via fallback in src/audio/mp3music.js; a "finale.mp3" covers World 4.
// Any id present here REPLACES the synth for that track; absent ids keep the synth.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MUSIC_DIR = path.join(ROOT, "public", "music");
const MANIFEST = path.join(ROOT, "src", "audio", "music_manifest.js");

// The ids the engine can actually use (exact tracks + world groups + finale).
const KNOWN = new Set([
  "title", "hub",
  "w1l1", "w1l2", "w1l3", "w2l1", "w2l2", "w2l3", "w3", "w4",
  "w1", "w2", "finale",
]);

async function main() {
  await fs.mkdir(MUSIC_DIR, { recursive: true });
  let files = [];
  try {
    files = (await fs.readdir(MUSIC_DIR))
      .filter((f) => f.toLowerCase().endsWith(".mp3"))
      .map((f) => f.replace(/\.mp3$/i, ""));
  } catch { /* dir absent -> empty */ }

  const ids = [...new Set(files)].sort();
  const unknown = ids.filter((id) => !KNOWN.has(id));
  if (unknown.length) {
    console.warn(`  ⚠ these files don't match a known track id (they'll be ignored by the game):`);
    for (const u of unknown) console.warn(`     public/music/${u}.mp3`);
    console.warn(`     known ids: ${[...KNOWN].join(", ")}`);
  }
  const usable = ids.filter((id) => KNOWN.has(id));

  const src =
    "// AUTO-GENERATED by tools/gen_music_manifest.mjs — do not edit by hand.\n" +
    "// The list of track ids that have a produced MP3 in public/music/<id>.mp3.\n" +
    "// Empty = the game plays its procedural synth music for every track (default).\n" +
    "// Drop MP3s in public/music/ and re-run the generator to populate this.\n" +
    `export const MUSIC_FILES = ${JSON.stringify(usable)};\n`;
  await fs.writeFile(MANIFEST, src);
  console.log(`  music manifest: ${usable.length} track(s) -> ${usable.join(", ") || "(none — synth fallback)"}`);
  console.log(`  wrote ${path.relative(ROOT, MANIFEST)}`);
}

main().catch((e) => { console.error(e.message || e); process.exit(1); });
