// Scan public/sfx/*.{wav,mp3} and regenerate src/audio/sfxsamples_manifest.js —
// the map of sfx voice name -> file extension for produced samples. Run after
// adding/removing sound files:
//
//   node tools/gen_sfx_manifest.mjs
//
// A file named <voice>.wav replaces that synth voice in-game (see the wrap in
// src/audio/sfx.js). Absent names keep the synth. WAV preferred (short, lossless);
// MP3 also accepted. If both exist for a name, WAV wins.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SFX_DIR = path.join(ROOT, "public", "sfx");
const MANIFEST = path.join(ROOT, "src", "audio", "sfxsamples_manifest.js");

// The primary voice names worth sampling (from src/audio/sfx.js). Files not in this
// set still work if their name matches a real voice, but a warning flags likely typos.
const KNOWN = new Set([
  "jump", "land", "stompLaunch", "stomp", "zip", "hangLatch", "reel", "grab",
  "throwIt", "tossHigh", "hopOff", "buddyBeep", "die", "respawn", "phaseIn",
  "phaseOut", "equip", "lever", "platePress", "plateRelease", "door", "doorClose",
  "exitDoor", "checkpoint", "key", "lockTurn", "core", "coresFanfare", "squish",
  "bugBounce", "bugBonk", "rollerAlert", "rollerZap", "wardenShove", "wardenTopple",
  "crush", "craneAlarm", "craneSlam", "craneYank", "podCrunch", "craneDefeat",
  "magnetOn", "magnetOff", "bubbleOn", "bubblePop", "splash",
  "menuMove", "menuSelect", "menuDeny", "saveTick", "settingsTick", "muteChirp",
  "pickup", "denied",
  // finale — KOBI's Heart boss + rescue (see docs/FINALE_AUDIO_BRIEF.md)
  "heartAlarm", "heartGlare", "heartSquint", "heartUnplug", "heartDown",
  "ventBlow", "boltYip",
]);

async function main() {
  await fs.mkdir(SFX_DIR, { recursive: true });
  let files = [];
  try {
    files = (await fs.readdir(SFX_DIR)).filter((f) => /\.(wav|mp3)$/i.test(f));
  } catch { /* empty */ }

  // name -> ext, WAV preferred over MP3
  const map = {};
  const unknown = [];
  for (const f of files.sort()) {
    const ext = f.toLowerCase().endsWith(".wav") ? "wav" : "mp3";
    const name = f.replace(/\.(wav|mp3)$/i, "");
    if (!KNOWN.has(name)) { unknown.push(f); continue; }
    if (map[name] === "wav") continue; // WAV already claimed this name
    map[name] = ext;
  }
  if (unknown.length) {
    console.warn("  ⚠ these files don't match a known sfx voice (ignored by the game):");
    for (const u of unknown) console.warn(`     public/sfx/${u}`);
  }

  const ordered = Object.fromEntries(Object.keys(map).sort().map((k) => [k, map[k]]));
  const src =
    "// AUTO-GENERATED by tools/gen_sfx_manifest.mjs — do not edit by hand.\n" +
    "// Map of sfx voice name -> file extension for produced samples in public/sfx/.\n" +
    "// Empty = every sound uses its procedural synth voice (default). Drop\n" +
    "// public/sfx/<name>.wav (or .mp3) and re-run the generator to populate this.\n" +
    `export const SFX_SAMPLES = ${JSON.stringify(ordered, null, 2)};\n`;
  await fs.writeFile(MANIFEST, src);
  const n = Object.keys(ordered).length;
  console.log(`  sfx manifest: ${n} sample(s) -> ${Object.keys(ordered).join(", ") || "(none — synth fallback)"}`);
  console.log(`  wrote ${path.relative(ROOT, MANIFEST)}`);
}

main().catch((e) => { console.error(e.message || e); process.exit(1); });
